name: hand_signature
description: The signature pad widget that allows to draw signature with finger.
homepage: https://basecontrol.dev
version: 0.5.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.0.8

  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
